// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1) {
  return window['go']['dnsapi']['DNSAPI']['CreateRecord'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['dnsapi']['DNSAPI']['DeleteRecord'](arg1);
}

export function GetRecordByAssetID(arg1) {
  return window['go']['dnsapi']['DNSAPI']['GetRecordByAssetID'](arg1);
}

export function GetStatus() {
  return window['go']['dnsapi']['DNSAPI']['GetStatus']();
}

export function ListQueryLogs(arg1) {
  return window['go']['dnsapi']['DNSAPI']['ListQueryLogs'](arg1);
}

export function ListRecords(arg1) {
  return window['go']['dnsapi']['DNSAPI']['ListRecords'](arg1);
}

export function SetRecordEnabled(arg1, arg2) {
  return window['go']['dnsapi']['DNSAPI']['SetRecordEnabled'](arg1, arg2);
}

export function UpdateRecord(arg1) {
  return window['go']['dnsapi']['DNSAPI']['UpdateRecord'](arg1);
}
