// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dnsapi} from '../models';

export function CreateRecord(arg1:dnsapi.CreateDNSRecordReq):Promise<dnsapi.Result_EnvPilot_internal_dns_model_DNSRecord_>;

export function DeleteRecord(arg1:number):Promise<dnsapi.Result_bool_>;

export function GetRecordByAssetID(arg1:number):Promise<dnsapi.Result_EnvPilot_internal_dns_model_DNSRecord_>;

export function GetStatus():Promise<dnsapi.Result_EnvPilot_internal_dns_service_RuntimeStatus_>;

export function ListQueryLogs(arg1:dnsapi.ListDNSQueryLogsReq):Promise<dnsapi.Result_EnvPilot_internal_dns_service_ListQuerySummariesResult_>;

export function ListRecords(arg1:dnsapi.ListDNSRecordsReq):Promise<dnsapi.Result___EnvPilot_internal_dns_model_DNSRecord_>;

export function SetRecordEnabled(arg1:number,arg2:boolean):Promise<dnsapi.Result_EnvPilot_internal_dns_model_DNSRecord_>;

export function UpdateRecord(arg1:dnsapi.UpdateDNSRecordReq):Promise<dnsapi.Result_EnvPilot_internal_dns_model_DNSRecord_>;
