// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configapi} from '../models';

export function GetCurrent():Promise<configapi.Result_EnvPilot_internal_config_service_CurrentConfigResult_>;

export function GetSnapshot(arg1:number):Promise<configapi.Result_EnvPilot_internal_config_service_SnapshotDetailResult_>;

export function ListSnapshots(arg1:configapi.ListSnapshotsReq):Promise<configapi.Result_EnvPilot_internal_config_service_ListSnapshotsResult_>;

export function Rollback(arg1:configapi.RollbackConfigReq):Promise<configapi.Result_EnvPilot_internal_config_service_CurrentConfigResult_>;

export function Update(arg1:configapi.UpdateConfigReq):Promise<configapi.Result_EnvPilot_internal_config_service_CurrentConfigResult_>;
