// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrent() {
  return window['go']['configapi']['ConfigAPI']['GetCurrent']();
}

export function GetSnapshot(arg1) {
  return window['go']['configapi']['ConfigAPI']['GetSnapshot'](arg1);
}

export function ListSnapshots(arg1) {
  return window['go']['configapi']['ConfigAPI']['ListSnapshots'](arg1);
}

export function Rollback(arg1) {
  return window['go']['configapi']['ConfigAPI']['Rollback'](arg1);
}

export function Update(arg1) {
  return window['go']['configapi']['ConfigAPI']['Update'](arg1);
}
