// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {connectorapi} from '../models';
import {context} from '../models';

export function ExecuteRedisCmd(arg1:service.ExecuteRedisCommandRequest):Promise<connectorapi.Result_EnvPilot_internal_connector_CommandResult_>;

export function ExecuteSQL(arg1:service.ExecuteSQLRequest):Promise<connectorapi.Result_EnvPilot_internal_connector_QueryResult_>;

export function ListDatabases(arg1:number):Promise<connectorapi.Result___string_>;

export function ListTables(arg1:connectorapi.ListTablesReq):Promise<connectorapi.Result___string_>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:number):Promise<connectorapi.Result_bool_>;
