// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRedisCmd(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['ExecuteRedisCmd'](arg1);
}

export function ExecuteSQL(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['ExecuteSQL'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['ListDatabases'](arg1);
}

export function ListTables(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['ListTables'](arg1);
}

export function SendMQMessage(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['SendMQMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['SetContext'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['connectorapi']['ConnectorAPI']['TestConnection'](arg1);
}
