// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAll(arg1) {
  return window['go']['healthapi']['HealthAPI']['CheckAll'](arg1);
}

export function CheckAsset(arg1) {
  return window['go']['healthapi']['HealthAPI']['CheckAsset'](arg1);
}

export function GetSummary(arg1) {
  return window['go']['healthapi']['HealthAPI']['GetSummary'](arg1);
}

export function ListSnapshots(arg1) {
  return window['go']['healthapi']['HealthAPI']['ListSnapshots'](arg1);
}
