// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {healthapi} from '../models';

export function CheckAll(arg1:healthapi.CheckAllReq):Promise<healthapi.Result_EnvPilot_internal_health_service_CheckAllResult_>;

export function CheckAsset(arg1:number):Promise<healthapi.Result_EnvPilot_internal_health_model_HealthSnapshot_>;

export function GetSummary(arg1:healthapi.ListSnapshotsReq):Promise<healthapi.Result_EnvPilot_internal_health_service_SummaryResult_>;

export function ListSnapshots(arg1:healthapi.ListSnapshotsReq):Promise<healthapi.Result_EnvPilot_internal_health_service_ListSnapshotsResult_>;
