// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backupapi} from '../models';

export function AnalyzeImportBackup(arg1:backupapi.AnalyzeImportReq):Promise<backupapi.Result_EnvPilot_internal_backup_service_AnalyzeImportResult_>;

export function ExportBackup():Promise<backupapi.Result_EnvPilot_internal_backup_api_ExportBackupResult_>;

export function ImportBackup(arg1:backupapi.ImportBackupReq):Promise<backupapi.Result_EnvPilot_internal_backup_service_ImportBackupResult_>;
