// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImportBackup(arg1) {
  return window['go']['backupapi']['BackupAPI']['AnalyzeImportBackup'](arg1);
}

export function ExportBackup() {
  return window['go']['backupapi']['BackupAPI']['ExportBackup']();
}

export function ImportBackup(arg1) {
  return window['go']['backupapi']['BackupAPI']['ImportBackup'](arg1);
}
