// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAsset(arg1) {
  return window['go']['assetapi']['AssetAPI']['CreateAsset'](arg1);
}

export function CreateCredential(arg1) {
  return window['go']['assetapi']['AssetAPI']['CreateCredential'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['assetapi']['AssetAPI']['CreateEnvironment'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['assetapi']['AssetAPI']['CreateGroup'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['assetapi']['AssetAPI']['DeleteAsset'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['assetapi']['AssetAPI']['DeleteCredential'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['assetapi']['AssetAPI']['DeleteEnvironment'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['assetapi']['AssetAPI']['DeleteGroup'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['assetapi']['AssetAPI']['GetAsset'](arg1);
}

export function GetPluginSchema(arg1) {
  return window['go']['assetapi']['AssetAPI']['GetPluginSchema'](arg1);
}

export function ListAssets(arg1) {
  return window['go']['assetapi']['AssetAPI']['ListAssets'](arg1);
}

export function ListCredentials() {
  return window['go']['assetapi']['AssetAPI']['ListCredentials']();
}

export function ListEnvironments() {
  return window['go']['assetapi']['AssetAPI']['ListEnvironments']();
}

export function ListGroupsByEnvironment(arg1) {
  return window['go']['assetapi']['AssetAPI']['ListGroupsByEnvironment'](arg1);
}

export function ListPlugins(arg1) {
  return window['go']['assetapi']['AssetAPI']['ListPlugins'](arg1);
}

export function RevealCredential(arg1) {
  return window['go']['assetapi']['AssetAPI']['RevealCredential'](arg1);
}

export function UpdateAsset(arg1) {
  return window['go']['assetapi']['AssetAPI']['UpdateAsset'](arg1);
}

export function UpdateCredential(arg1) {
  return window['go']['assetapi']['AssetAPI']['UpdateCredential'](arg1);
}

export function UpdateEnvironment(arg1) {
  return window['go']['assetapi']['AssetAPI']['UpdateEnvironment'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['assetapi']['AssetAPI']['UpdateGroup'](arg1);
}
