// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assetapi} from '../models';

export function CreateAsset(arg1:assetapi.CreateAssetReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Asset_>;

export function CreateCredential(arg1:assetapi.CreateCredentialReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Credential_>;

export function CreateEnvironment(arg1:assetapi.CreateEnvironmentReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Environment_>;

export function CreateGroup(arg1:assetapi.CreateGroupReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Group_>;

export function DeleteAsset(arg1:number):Promise<assetapi.Result_bool_>;

export function DeleteCredential(arg1:number):Promise<assetapi.Result_bool_>;

export function DeleteEnvironment(arg1:number):Promise<assetapi.Result_bool_>;

export function DeleteGroup(arg1:number):Promise<assetapi.Result_bool_>;

export function GetAsset(arg1:number):Promise<assetapi.Result_EnvPilot_internal_asset_model_Asset_>;

export function ListAssets(arg1:assetapi.ListAssetsReq):Promise<assetapi.Result___EnvPilot_internal_asset_model_Asset_>;

export function ListCredentials():Promise<assetapi.Result___EnvPilot_internal_asset_model_Credential_>;

export function ListEnvironments():Promise<assetapi.Result___EnvPilot_internal_asset_model_Environment_>;

export function ListGroupsByEnvironment(arg1:number):Promise<assetapi.Result___EnvPilot_internal_asset_model_Group_>;

export function UpdateAsset(arg1:assetapi.UpdateAssetReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Asset_>;

export function UpdateCredential(arg1:assetapi.UpdateCredentialReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Credential_>;

export function UpdateEnvironment(arg1:assetapi.UpdateEnvironmentReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Environment_>;

export function UpdateGroup(arg1:assetapi.UpdateGroupReq):Promise<assetapi.Result_EnvPilot_internal_asset_model_Group_>;
