// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExecuteCommand(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['BatchExecuteCommand'](arg1);
}

export function CheckDangerousCommand(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['CheckDangerousCommand'](arg1);
}

export function Cleanup() {
  return window['go']['executorapi']['ExecutorAPI']['Cleanup']();
}

export function CloseTerminal(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['CloseTerminal'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['ExecuteCommand'](arg1);
}

export function GetExecution(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['GetExecution'](arg1);
}

export function ListExecutions(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['ListExecutions'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['executorapi']['ExecutorAPI']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['SetContext'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['executorapi']['ExecutorAPI']['StartTerminal'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['executorapi']['ExecutorAPI']['TerminalInput'](arg1, arg2);
}
