// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CreateAsset(arg1:api.CreateAssetReq):Promise<api.Result_EnvPilot_internal_asset_model_Asset_>;

export function CreateCredential(arg1:api.CreateCredentialReq):Promise<api.Result_EnvPilot_internal_asset_model_Credential_>;

export function CreateEnvironment(arg1:api.CreateEnvironmentReq):Promise<api.Result_EnvPilot_internal_asset_model_Environment_>;

export function CreateGroup(arg1:api.CreateGroupReq):Promise<api.Result_EnvPilot_internal_asset_model_Group_>;

export function DeleteAsset(arg1:number):Promise<api.Result_bool_>;

export function DeleteCredential(arg1:number):Promise<api.Result_bool_>;

export function DeleteEnvironment(arg1:number):Promise<api.Result_bool_>;

export function DeleteGroup(arg1:number):Promise<api.Result_bool_>;

export function GetAsset(arg1:number):Promise<api.Result_EnvPilot_internal_asset_model_Asset_>;

export function ListAssets(arg1:api.ListAssetsReq):Promise<api.Result___EnvPilot_internal_asset_model_Asset_>;

export function ListCredentials():Promise<api.Result___EnvPilot_internal_asset_model_Credential_>;

export function ListEnvironments():Promise<api.Result___EnvPilot_internal_asset_model_Environment_>;

export function ListGroupsByEnvironment(arg1:number):Promise<api.Result___EnvPilot_internal_asset_model_Group_>;

export function UpdateAsset(arg1:api.UpdateAssetReq):Promise<api.Result_EnvPilot_internal_asset_model_Asset_>;

export function UpdateCredential(arg1:api.UpdateCredentialReq):Promise<api.Result_EnvPilot_internal_asset_model_Credential_>;

export function UpdateEnvironment(arg1:api.UpdateEnvironmentReq):Promise<api.Result_EnvPilot_internal_asset_model_Environment_>;

export function UpdateGroup(arg1:api.UpdateGroupReq):Promise<api.Result_EnvPilot_internal_asset_model_Group_>;
