// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auditapi} from '../models';

export function CleanupAuditLogs():Promise<auditapi.Result_EnvPilot_internal_audit_service_CleanupResult_>;

export function ListAuditLogs(arg1:auditapi.ListAuditLogsReq):Promise<auditapi.Result_EnvPilot_internal_audit_service_ListResult_>;
