// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupAuditLogs() {
  return window['go']['auditapi']['AuditAPI']['CleanupAuditLogs']();
}

export function ListAuditLogs(arg1) {
  return window['go']['auditapi']['AuditAPI']['ListAuditLogs'](arg1);
}
