// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hostinfo} from '../models';

export function GetHostInfo():Promise<hostinfo.Snapshot>;

export function GetVersion():Promise<Record<string, string>>;

export function Ping():Promise<string>;
