// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hostinfo} from '../models';
import {main} from '../models';

export function GetHostInfo():Promise<hostinfo.Snapshot>;

export function GetLaunchContext():Promise<main.LaunchContext>;

export function GetVersion():Promise<Record<string, string>>;

export function OpenTerminalWindow(arg1:number):Promise<void>;

export function Ping():Promise<string>;

export function SaveExportFile(arg1:main.SaveExportFileReq):Promise<string>;
