// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetLaunchContext() {
  return window['go']['main']['App']['GetLaunchContext']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenTerminalWindow(arg1) {
  return window['go']['main']['App']['OpenTerminalWindow'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveExportFile(arg1) {
  return window['go']['main']['App']['SaveExportFile'](arg1);
}
