// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['authapi']['AuthAPI']['ChangePassword'](arg1);
}

export function GetStatus() {
  return window['go']['authapi']['AuthAPI']['GetStatus']();
}

export function Lock() {
  return window['go']['authapi']['AuthAPI']['Lock']();
}

export function Setup(arg1) {
  return window['go']['authapi']['AuthAPI']['Setup'](arg1);
}

export function Unlock(arg1) {
  return window['go']['authapi']['AuthAPI']['Unlock'](arg1);
}
