// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {authapi} from '../models';

export function ChangePassword(arg1:authapi.ChangePasswordReq):Promise<authapi.Result_EnvPilot_internal_auth_service_Status_>;

export function GetStatus():Promise<authapi.Result_EnvPilot_internal_auth_service_Status_>;

export function Lock():Promise<authapi.Result_bool_>;

export function Setup(arg1:authapi.UnlockReq):Promise<authapi.Result_EnvPilot_internal_auth_service_Status_>;

export function Unlock(arg1:authapi.UnlockReq):Promise<authapi.Result_EnvPilot_internal_auth_service_Status_>;
